# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddproductcheckout():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addproductcheckout(self):
    # Test name: add_product_checkout
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 706x728 | 
    self.driver.set_window_size(706, 728)
    # 3 | click | css=*[data-test="username"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    # 4 | type | css=*[data-test="username"] | standard_user
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    # 5 | click | css=*[data-test="password"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    # 6 | type | css=*[data-test="password"] | secret_sauce
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    # 7 | sendKeys | css=*[data-test="password"] | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys(Keys.ENTER)
    # 8 | click | css=*[data-test="add-to-cart-sauce-labs-backpack"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    # 9 | mouseOver | css=*[data-test="add-to-cart-sauce-labs-backpack"] | 
    element = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | click | css=.shopping_cart_badge | 
    self.driver.find_element(By.CSS_SELECTOR, ".shopping_cart_badge").click()
    # 11 | click | css=*[data-test="checkout"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
    # 12 | click | css=*[data-test="firstName"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
    # 13 | type | css=*[data-test="firstName"] | aaa
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("aaa")
    # 14 | click | css=*[data-test="lastName"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").click()
    # 15 | type | css=*[data-test="lastName"] | bb
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("bb")
    # 16 | click | css=*[data-test="postalCode"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").click()
    # 17 | type | css=*[data-test="postalCode"] | 66666
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("66666")
    # 18 | click | css=*[data-test="continue"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    # 19 | click | css=*[data-test="finish"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
    # 20 | click | css=*[data-test="back-to-products"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
  
